### ISSUE TITLE
Gerir Investigadores

### ISSUE THREAD

**Issue by Joselpsantos** [ci2-ipt/Ci2-CRIS#2]
Como utilizador quero ser capaz de realizar operações CRUD nos investigadores.

**Comment by renatopanda** [comment]
@Joselpsantos e @joaodomingues4 não sei se aqui é o melhor local mas ainda assim aqui vai. Com as últimas reuniões fomos ganhando uma melhor noção do que se pretende. No caso do Researcher, representa uma pessoa (investigador) que pertence a um centro de investigação e a uma instituição.

Dando exemplos:
* Eu estou afiliado ao Ci2 como membro integrado a 100% e tenho contrato com a instituição IPT.
* O professor Gabriel está afiliado ao Ci2 como membro colaborador a 10%, estando integrado no ISR (centro de investigação da UC) como membro integrado a 40%. O professor Gabriel tem vínculo de professor com o IPT.
* O professor Mário é professor na UAL (instituição), investigador colaborador do Ci2 a 20% e investigador/membro integrado noutro centro de Investigação.

Seria interessante um dia conseguir capturar isto, no entanto sugiro que se foque no que mais importa primeiro:
1. Investigadores (researchers ou persons)
2. Projetos de Investigação (projects)
3. Trabalhos/artigos (works ou outputs)

Na parte da afiliação planeamos a existência de Centros de Investigação e Instituições mas por exemplo o CV resolve o problema usando apenas um "Institution/Organization" com estes campos:
![image](https://user-images.githubusercontent.com/1618980/209002880-61935621-681b-4627-a36b-a29636e5e075.png)

Voltando à questão dos investigadores, pensando nos conceitos KISS e YAGNI, focando no nosso problema - plataforma para o centro de investigação Ci2 do IPT. O que pretendemos como story/funcionalidade base é simples:
1. Que eu, tendo uma conta com privilégios de administrador ou gestor, consiga criar novas pessoas/investigadores (CRUD Researcher).
2. Que uma pessoa com uma conta *autorizada* consiga gerir o seu perfil de investigador, criando/editando/apagando projetos e trabalhos.
3. Que um visitante não autenticado consiga ver esses dados públicos.

Não se pretende que qualquer pessoa aleatória se consiga registar, pois não é um portal público. Pretende-se apenas que os Researchers **do ci2** que forem criados possam ter o controlo do seu perfil. Isto vai implicar que se estude a melhor forma de fazer esta gestão / criação de Researcher Profile + User Account e posterior ligação ao Azure AD ( cc/ @curiousyigit )

Numa primeira fase (e não vamos ter muitas, portanto eu sugeria nas próximas semanas) era bom que mesmo sem termos Auth* a funcionar correctamente, era bom que existisse:
1. O CRUD funcional destes 3 modelos centrais (Person ou Researcher, Work com STI, Project)
2. Eventualmente com ligação aos outros modelos acessórios (Institution/Organization/ResearchCenter, Lab)
3. Futuramente com a parte de contas de User ligadas ao Researchers do Ci2, com possibilidade de autenticação via Azure AD, assim como Roles definidos para essas contas.

Se quiserem podemos reunir na próxima semana por VC para discutir algumas destas ideias. A 3ª parte terá que ser bem pensada em termos de funcionalidade. Idealmente eu imagino que um manager/admin possa gerir Researchers e User Accounts, assim como Roles. Ao criar um novo Researcher vai criar uma conta de user e enviar um email a avisar. Não?

**Comment by renatopanda** [comment]
> Concordo com o que professor disse e relativamente à criação de contas de Researchers, o admin é que sabe que tem de criar um Researcher ou existe algum requerimento? Por exemplo, eu como utilizador registado quero passar a assumir o papel de Researcher, posso simplesmente colocar os meus dados num formulário e submeto-o, do outro lado o admin pode aceitar ou recusar o meu request?
> 
> Outra questão que me levantou foi a afiliação de um Researcher a uma instituição e a um centro de investigação, é o próprio admin vai controlar este tema? No caso de existir um responsável por cada instituição/centro vai libertar trabalho ao admin da aplicação e vai eliminar a necessidade de distribuir o role admin por vários users (dependendo se a gestão da plataforma é suposta ser feita por mais que uma pessoa).

Vamos manter uma abordagem simples. Estamos a falar do SI para um centro de investigação específico (Ci2), logo os investigadores que usam o site terão de ser membros do mesmo. Num cenário ainda mais simplista nem tínhamos centros, no entanto como é normal haver colaborações, vai existir necessidade de criar investigadores externos ao Ci2 (sem conta de utilizador), que participam em projetos e trabalhos.

Assim e respondendo directamente às questões:
1. Os membros são adicionados por alguém da direcção do centro (ou seja, com role de manager / admin).
2. Não há portanto um membro que se registe de livre vontade, há um utilizador com privilégios que cria uma conta e, se necessário, associa a mesma ao perfil de um utilizador. Exemplificando, a) o José Santos torna-se membro do Ci2, então é criado um perfil de investigador José Santos, preenchidos os dados, e criada a conta de utilizador para que possa fazer a gestão dos seus dados. b) O José Santos entra no site com a sua conta e decide inserir um projeto de investigação em que participa. Para isso cria o projeto e vai associar os investigadores envolvidos no projecto. Um dos investigadores é o João Domingues, que pertence ao centro externo X, neste caso terá de criar um investigador (externo) e provavelmente um centro (externo também) ao qual o João Domingues está associado. Estes devem ser sempre identificados via ORCID.
3. Em relação aos roles depois serão dados conforme necessário, a maioria não terá capacidade de admin mas deve conseguir criar investigadores e centros externos ou coisas do género. Diria que trabalharemos nisso numa iteração futura. No entanto mantenham sempre em mente que aqui o foco é o centro Ci2 do IPT, portanto os dados relativos a outros centros e investigadores servem mesmo só para catalogar a informação adicional.

Se necessário podemos falar para a semana via Teams/Zoom para discutirmos isto. Cada nova discussão torna a ideia mais clara para ambas as partes 😄
