### ISSUE TITLE
Gerir Trabalhos

### ISSUE THREAD

**Issue by Joselpsantos** [ci2-ipt/Ci2-CRIS#4]
Como utilizador quero ser capaz de realizar operações CRUD
- [x] #8

**Comment by renatopanda** [comment]
@Joselpsantos , tal como prometido fica aqui um pouco de informação que por norma existe nos trabalhos. O trabalho por norma um documento, ou seja um artigo onde um grupo de investigadores descreve o que foi feito. Um artigo pode de vários tipos, como de revista científica, publicado em conferências ou até parte de um livro (chamado de capítulo).

O que o CRIS guarda são os detalhes dos tais artigos que são publicados pelos investigadores afectos ao centro (Ci2), que por vezes pode ser em conjunto com investigadores de outros centros (ou sem centro).

Sobre os tais artigos, alguns dados.


Journal article:
- Title
- Authors
- Journal name
- Year (or also month and day)
- Volume
- Issue
- Pages (X to Y)
- Abstract
- Keywords
- URL
- IDs (DOI, handle, scopus, ...)

Conference Proceedings:
- Title
- Authors
- Proceedings Title (nome da conferência)
- Year
- Pages
- Abstract
- Keywords
- City/Place (da conf)
- URL
- IDs

Book Section/Chapter:
- Title
- Authors
- Book
- Year
- Pages
- Abstract
- Keywords
- Chapter no
- Publisher
- URL

Book:
- Title
- Authors
- Year
- Pages
- Abstract
- Keywords
- Edition
- Publisher
- URL
- IDs (DOI, handle, ISBN...)

Thesis
- Title
- Authors
- Year
- pages
- Abstract
- Keywords
- Department
- University
- Type
- URL
- IDs

Report
- Title
- Authors
- Year
- Pages
- Abstract
- Keywords
- URL
- IDs

Existem N outros tipos de publicações mas como conseguem ver anda tudo muito à volta do mesmo e partilham imensa coisa, daí a sugestão para usarem STI (herança com uma tabela).

Para além disto era interessante ter
publication scope (international/national)
student publication (true / false)
os autores têm ordem
o handle no fundo é um código/url que leva ao ficheiro no repositório institucional, por exemplo: http://hdl.handle.net/10400.26/42730
