### ISSUE TITLE
MAIN NÃO FUNCIONAL

### ISSUE THREAD

**Issue by Joselpsantos** [ci2-ipt/Ci2-CRIS#67]
O CONTAINER NÃO PÁRA DE RESETAR

**Comment by renatopanda** [comment]
Nota: não estou por dentro dos vários problemas que provavelmente existem no vosso projeto. Disto isto, fica aqui uma explicação para o facto do vosso schema.db ser alterado volta e meia (que foi o problema reportado pelo ontem @curiousyigit )

TL;DR: o problema deverá ser a mudança entre branches sem fazer reset à DB (fica inconsistente) e o facto do migrate fazer **sempre** db:schema:dump da BD no fim para o schema.db (segundo isto https://stackoverflow.com/a/72162169/5145402 ). **FAZER SEMPRE `rails db:reset` ao mudar de branch**.

Uma explicação um pouco mais longa:
Os modelos do projeto são classes (código no git), no entanto estes dados são persistidos (guardados) num sistema de bases de dados externo ao código/git/repositório. Corre num serviço em separado (mariadb, o segundo container que têm a correr). As alterações à BD são feitas através das migrações, como sabem, que levam a BD de um ponto A para o ponto B. Daí que seja importante manter a consistência das mesmas, manter a sua ordem e não editar migrações que já se encontram no repositório (aqui a solução é fazer nova migração para corrigir o problema, ou seja A -> B -> C ( em que C reverte o estado para A).

Percebendo isto, torna-se claro que andar a mudar de branch não dando reset na DB vai tornar a BD inconsistente.

### Exemplo prático
1. Vamos imaginar que o @curiousyigit está a meio do desenvolvimento de uma feature no branch B1, onde criou uma migração M1 para criar a tabela `users` e aplicou a mesma. A base de dados (ci2_cris) contém a tabela `users` e o `schema.rb` nesse branch (B1) também.
2. Se o @curiousyigit entretanto saltar para o branch B2, para ajudar o @Joselpsantos , vai ter o schema.rb desse branch na sua pasta db/schema.rb. No entanto, a BD que está a correr não foi alterada (ci2_cris no container mariadb), continua a conter a tabela users, que o @Joselpsantos ainda não tem no branch B2.
3. Vamos imaginar que o @Joselpsantos entretanto já criou uma nova migração M2 para adicionar a tabela `articles`. Se o @curiousyigit executar `rails db:migrate` ele vai **aplicar as migrações novas** na sua BD actual, criando a tabela `articles`. No fim faz dump do schema e este será diferente do `schema.rb` atual (provavelmente corrompendo o mesmo.
4. Entretanto se o @curiousyigit voltar ao seu branch B1, executar `rails db:migrate` não vai aplicar alteração alguma à BD, pois não existem migrações novas, no entanto o dump do schema vai gerar um ficheiro diferente (pois a BD presente no container do    @curiousyigit contém agora uma tabela `articles`, que não devia existir neste branch B1.
5. Isto vai fazer com que o git se queixe que há uma alteração e vai levar o ERD a ser gerado de novo. Já agora, a framework sabe as migrações a aplicar vendo as que foram aplicadas na tabela `schema_migrations` presente na DB.

Percebido o problema?

### Como resolver?
A solução é óbvia: sempre que mudarem entre branches devem fazer reset à base de dados. Para isso devem executar **sempre** `rails db:reset`. Isto vai destruir a BD atual, carregar a mesma com base no schema.rb existente e carregar as seeds.

À partida nem precisam de executar `db:migrate`, mas podem e isto não deve alterar o schema.rb (a não ser que haja migrações pendentes em relação ao schema.rb). Imagino que a pessoa que abre um PR antes fez merge do main para o seu branch, executou o `db:migrate` e fará commit do schema.rb válido e atualizado.

Outras notas (@Joselpsantos abrir tickets se achares importante, ou corrigir diretamente no trabalho em curso):
* Se acham que a BD e schema.rb do vosso branch estão com problemas, podem sempre recriar tudo via migrações `rails db:migrate:reset`. Também podem fazer `rails db:drop db:setup db:migrate db:seed` e coisas do género (parte destes comandos repetem chamam os outros).
* O @Joselpsantos tem uma migração vazia para criar uma relação artigos - projetos, falta uma linha a definir a referência / fk na tabela. Tanto que ao recriar a BD vão ver que a mesma linha desaparece do schema.rb. No entanto até pode-se pensar já em criar uma migração nova pois a relação é many-to-many. Pode ser via has_and_belongs_to_many para simplificar, ou has_many: through - https://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many. Isto implica criar a join table (`articles_projects`, se for para usar a convenção, ou em alternativa criar a join table `project_articles` (nome mais lógico?) e definir explicitamente o nome na ligação dos modelos - ver https://guides.rubyonrails.org/association_basics.html#creating-join-tables-for-has-and-belongs-to-many-associations. Ambas as opções servem.
* Existem gems definidas em duplicado. Não que haja problema mas é correr o `bin/setup` no container para ver o output.

**Comment by curiousyigit** [comment]
@Joselpsantos está foncionar sem problemas, só que tem erros na etapa de bundle install como o merge do ontem (https://github.com/ci2-ipt/Ci2-CRIS/commit/6ca3803130546766e7483ce27f7c152ad24df092) adicionou gems duplicados no Gemfile:
```
Your Gemfile lists the gem devise (~> 4.8) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem mail_form (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem jquery-rails (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
Your Gemfile lists the gem bootstrap (~> 5.2.2) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
```
Más este não impede de correr a aplicação e os containers. Provavelmente tu tens outros problems (voces costumam de ter errors com git e file permissions, etc.). Eu já testei no meu local de zero, e deu sem problemas. Tens que ver os logs do container para perceber porque é que está num restart loop.

**Comment by curiousyigit** [comment]
> Nota: não estou por dentro dos vários problemas que provavelmente existem no vosso projeto. Disto isto, fica aqui uma explicação para o facto do vosso schema.db ser alterado volta e meia (que foi o problema reportado pelo ontem @curiousyigit )
> 
> TL;DR: o problema deverá ser a mudança entre branches sem fazer reset à DB (fica inconsistente) e o facto do migrate fazer **sempre** db:schema:dump da BD no fim para o schema.db (segundo isto https://stackoverflow.com/a/72162169/5145402 ). **FAZER SEMPRE `rails db:reset` ao mudar de branch**.
> 
> Uma explicação um pouco mais longa: Os modelos do projeto são classes (código no git), no entanto estes dados são persistidos (guardados) num sistema de bases de dados externo ao código/git/repositório. Corre num serviço em separado (mariadb, o segundo container que têm a correr). As alterações à BD são feitas através das migrações, como sabem, que levam a BD de um ponto A para o ponto B. Daí que seja importante manter a consistência das mesmas, manter a sua ordem e não editar migrações que já se encontram no repositório (aqui a solução é fazer nova migração para corrigir o problema, ou seja A -> B -> C ( em que C reverte o estado para A).
> 
> Percebendo isto, torna-se claro que andar a mudar de branch não dando reset na DB vai tornar a BD inconsistente.
> 
> ### Exemplo prático
> 1. Vamos imaginar que o @curiousyigit está a meio do desenvolvimento de uma feature no branch B1, onde criou uma migração M1 para criar a tabela `users` e aplicou a mesma. A base de dados (ci2_cris) contém a tabela `users` e o `schema.rb` nesse branch (B1) também.
> 2. Se o @curiousyigit entretanto saltar para o branch B2, para ajudar o @Joselpsantos , vai ter o schema.rb desse branch na sua pasta db/schema.rb. No entanto, a BD que está a correr não foi alterada (ci2_cris no container mariadb), continua a conter a tabela users, que o @Joselpsantos ainda não tem no branch B2.
> 3. Vamos imaginar que o @Joselpsantos entretanto já criou uma nova migração M2 para adicionar a tabela `articles`. Se o @curiousyigit executar `rails db:migrate` ele vai **aplicar as migrações novas** na sua BD actual, criando a tabela `articles`. No fim faz dump do schema e este será diferente do `schema.rb` atual (provavelmente corrompendo o mesmo.
> 4. Entretanto se o @curiousyigit voltar ao seu branch B1, executar `rails db:migrate` não vai aplicar alteração alguma à BD, pois não existem migrações novas, no entanto o dump do schema vai gerar um ficheiro diferente (pois a BD presente no container do    @curiousyigit contém agora uma tabela `articles`, que não devia existir neste branch B1.
> 5. Isto vai fazer com que o git se queixe que há uma alteração e vai levar o ERD a ser gerado de novo. Já agora, a framework sabe as migrações a aplicar vendo as que foram aplicadas na tabela `schema_migrations` presente na DB.
> 
> Percebido o problema?
> 
> ### Como resolver?
> A solução é óbvia: sempre que mudarem entre branches devem fazer reset à base de dados. Para isso devem executar **sempre** `rails db:reset`. Isto vai destruir a BD atual, carregar a mesma com base no schema.rb existente e carregar as seeds.
> 
> À partida nem precisam de executar `db:migrate`, mas podem e isto não deve alterar o schema.rb (a não ser que haja migrações pendentes em relação ao schema.rb). Imagino que a pessoa que abre um PR antes fez merge do main para o seu branch, executou o `db:migrate` e fará commit do schema.rb válido e atualizado.
> 
> Outras notas (@Joselpsantos abrir tickets se achares importante, ou corrigir diretamente no trabalho em curso):
> 
> * Se acham que a BD e schema.rb do vosso branch estão com problemas, podem sempre recriar tudo via migrações `rails db:migrate:reset`. Também podem fazer `rails db:drop db:setup db:migrate db:seed` e coisas do género (parte destes comandos repetem chamam os outros).
> * O @Joselpsantos tem uma migração vazia para criar uma relação artigos - projetos, falta uma linha a definir a referência / fk na tabela. Tanto que ao recriar a BD vão ver que a mesma linha desaparece do schema.rb. No entanto até pode-se pensar já em criar uma migração nova pois a relação é many-to-many. Pode ser via has_and_belongs_to_many para simplificar, ou has_many: through - https://guides.rubyonrails.org/association_basics.html#choosing-between-has-many-through-and-has-and-belongs-to-many. Isto implica criar a join table (`articles_projects`, se for para usar a convenção, ou em alternativa criar a join table `project_articles` (nome mais lógico?) e definir explicitamente o nome na ligação dos modelos - ver https://guides.rubyonrails.org/association_basics.html#creating-join-tables-for-has-and-belongs-to-many-associations. Ambas as opções servem.
> * Existem gems definidas em duplicado. Não que haja problema mas é correr o `bin/setup` no container para ver o output.

Obrigado professor @renatopanda, já criei issues

**Comment by Joselpsantos** [comment]
O código do main já está a funçuminar
