### ISSUE TITLE
warning: shebang line ending with \r may cause problems

### ISSUE THREAD

**Issue by PaivaX** [ci2-ipt/Ci2-CRIS#7]
A tentar iniciar o server, dá-me esse erro.

Pelos vistos é derivado a ter sido criado num SO diferente. Estou a utilizar o WSL.

**Comment by Joselpsantos** [comment]
A solução está neste post.
https://stackoverflow.com/questions/54286602/how-to-fix-shebang-warning-in-ruby

Basta executarem os comandos:
git config --global core.autocrlf true
rails app:update:bin
