### ISSUE TITLE
Relação Articles - Projects é mal feito

### ISSUE THREAD

**Issue by curiousyigit** [ci2-ipt/Ci2-CRIS#71]
A relação entre Articles e Projetos é mal feito. Não devia mudar o schema manualmente. devia adicionar uma migração para fazer isso. De momento, cada vez que corremos db:migrate vai apagar as mudanças manuais no schema.rb. Provavelmente também foi este o problema do (https://github.com/ci2-ipt/Ci2-CRIS/pull/50)

![Image](https://user-images.githubusercontent.com/40928240/215904710-7252bf76-0328-4358-8674-ea3b74a8d7d8.png)

**Comment by curiousyigit** [comment]
@LammLamm12 o teu problema pode ser o mesmo

**Comment by LammLamm12** [comment]
> @LammLamm12 o teu problema pode ser o mesmo

É capaz do commit que fiz agora ter resolvido, é preciso ver

**Comment by Joselpsantos** [comment]
@curiousyigit vou fechar este issue uma vez que a associação que fiz não vai ser utilizada (em vez de 1-N passa para M-N).
